# Generated by Django 5.2.7 on 2025-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equbgroup',
            name='rotation_started',
            field=models.BooleanField(default=False),
        ),
    ]
