# Generated by Django 5.2.7 on 2025-10-13 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0003_account_is_verified_account_token_expiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equbgroup',
            name='current_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_equb_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
