# Generated by Django 5.2.7 on 2025-10-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0004_equbgroup_current_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='equbgroup',
            name='service_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of the total pot the creator takes as a service fee.', max_digits=5),
        ),
    ]
