# Generated by Django 5.2.7 on 2025-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(default='123456789', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_code',
            field=models.CharField(default='001', max_length=10),
            preserve_default=False,
        ),
    ]
